### ISSUE TITLE
live2d导出motions

### ISSUE THREAD

**Issue by wangguo1230** [colorfulshadowty/live-2d#1]
大佬 我想问一下,您知道用live2d editor如何导出motions文件吗,我这边只会导出.moc3的文件但是他不会动,不知道怎么样才能把动的也导出来
<img width="1214" alt="image" src="https://user-images.githubusercontent.com/39080510/80553482-956e0200-89fc-11ea-9409-2b70feeb3597.png">

**Comment by Colorfulshadow** [comment]
抱歉回复晚啦
editor可以导出moc版本的，只不过对版本有要求，似乎3.3版本及其以下才可以导出（不确定，反正版本越低越容易）
另外moc3格式的是可以动的，如果你是view预览可以把所有文件（包括motions）一起拖入exe，如果你是网站的话，moc3与moc版本用法有些许不用，具体可以参考Hclongly的这篇文章
[moc3用法](https://blog.hclonely.com/posts/8a7f7919/)
ps：使用moc3格式请注意js的版权问题

**Comment by wangguo1230** [comment]
谢谢啦,已经解决啦
